propel:
  database:
    connections:
      shop:
        adapter: sqlite
        # use the following config for production profile
        # classname: Propel\Runtime\Connection\ConnectionWrapper
        classname: Propel\Runtime\Connection\DebugPDO
        dsn: "sqlite:shop.db"
        user: "chris"
        password: "somepassword"
        settings:
          charset: utf8
  runtime:
      defaultConnection: shop
      log:
        # DEBUG (100): Detailed debug information.
        # INFO (200): Interesting events. Examples: User logs in, SQL logs.
        # NOTICE (250): Normal but significant events.
        # WARNING (300): Exceptional occurrences that are not errors. Examples: Use of deprecated APIs, poor use of an API, undesirable things that are not necessarily wrong.
        # ERROR (400): Runtime errors that do not require immediate action but should typically be logged and monitored.
        # CRITICAL (500): Critical conditions. Example: Application component unavailable, unexpected exception.
        # ALERT (550): Action must be taken immediately. Example: Entire website down, database unavailable, etc. This should trigger the SMS alerts and wake you up.
        # EMERGENCY (600): Emergency: system is unusable.
        defaultLogger:
          type: stream
          path: ../log/propel.log
          level: 100
        shop:
          type: stream
          path: ../log/propel_shop.log
          level: 100
      connections:
          - shop
  generator:
      defaultConnection: shop
      connections:
          - shop