propel:
  database:
    connections:
      shop:
        adapter: sqlite
        # use the following config for production profile
        # classname: Propel\Runtime\Connection\ConnectionWrapper
        classname: Propel\Runtime\Connection\DebugPDO
        dsn: "sqlite:shop.db"
        user: "chris"
        password: "somepassword"
        settings:
          charset: utf8
  runtime:
      defaultConnection: shop
      log:
        defaultLogger:
          type: stream
          path: log/propel.log
          level: 300
        shop:
          type: stream
          path: log/propel_shop.log
      connections:
          - shop
  generator:
      defaultConnection: shop
      connections:
          - shop